export const QUERY_CUSTOMER_LIST = 'customer/QUERY_CUSTOMER_LIST'

export const QUERY_CUSTOMER_QUICK_SEARCH_LIST = 'customer/QUERY_CUSTOMER_QUICK_SEARCH_LIST'
export const UPDATE_CUSTOMER_QUICK_SEARCH = 'customer/UPDATE_CUSTOMER_QUICK_SEARCH'

export const REFRESH_LEFT = 'customer/REFRESH_LEFT'
export const EMPTY_RIGHT = 'customer/EMPTY_RIGHT'
