export const QUERY_CALL_RELAY_TIME_REPORT = 'report/QUERY_CALL_RELAY_TIME_REPORT'
export const QUERY_CALL_RELAY_AREA_REPORT = 'report/QUERY_CALL_RELAY_AREA_REPORT'
export const QUERY_CALL_CALLOUT_TIME_REPORT = 'report/QUERY_CALL_CALLOUT_TIME_REPORT'
export const QUERY_CALL_DIALOUT_AREA_REPORT = 'report/QUERY_CALL_DIALOUT_AREA_REPORT'
export const QUERY_CALL_QUEUE_REPORT = 'report/QUERY_CALL_QUEUE_REPORT'
export const QUERY_CALL_QUEUE_TIME_REPORT = 'report/QUERY_CALL_QUEUE_TIME_REPORT'
export const QUERY_CALL_AGENT_REPORT = 'report/QUERY_CALL_AGENT_REPORT'
export const QUERY_CALL_APPROVE_SURVEY_REPORT = 'report/QUERY_CALL_APPROVE_SURVEY_REPORT'
export const OPEN_RELAY_AREA_CITY = 'report/OPEN_RELAY_AREA_CITY'
export const QUERY_AGENT_TIME = 'report/QUERY_AGENT_TIME'
export const QUERY_CALL_AGENT_REPORT_CTI = 'report/QUERY_CALL_AGENT_REPORT_CTI'

export const QUERY_IM_MESSAGE_REPORT = 'report/QUERY_IM_MESSAGE_REPORT'
export const QUERY_IM_BUSINESS_ANALYSE_REPORT = 'report/QUERY_IM_BUSINESS_ANALYSE_REPORT'
export const QUERY_IM_AGENT_REPORT = 'report/QUERY_IM_AGENT_REPORT'
export const QUERY_IM_CSR_REPORT = 'report/QUERY_IM_CSR_REPORT'
export const QUERY_IM_CHANNEL_CSR_REPORT = 'report/QUERY_IM_CHANNEL_CSR_REPORT'
export const QUERY_IM_SESSION_TIME_REPORT = 'report/QUERY_IM_SESSION_TIME_REPORT'
export const QUERY_IM_SESSION_FROM_REPORT = 'report/QUERY_IM_SESSION_FROM_REPORT'
export const QUERY_IM_AGENT_RESPONSE_REPORT = 'report/QUERY_IM_AGENT_RESPONSE_REPORT'

export const QUERY_MAIL_AGENT_REPORT = 'report/QUERY_MAIL_AGENT_REPORT'
export const QUERY_MAIL_CATEGORY_REPORT = 'report/QUERY_MAIL_CATEGORY_REPORT'

export const QUERY_CUSTOMER_INCREASE_REPORT = 'report/QUERY_CUSTOMER_INCREASE_REPORT'

export const QUERY_BUSINESS_ANALYSE_REPORT = 'report/QUERY_BUSINESS_ANALYSE_REPORT'
export const QUERY_BUSINESS_AGENT_REPORT = 'report/QUERY_BUSINESS_AGENT_REPORT'

export const QUERY_QUES_RESULT_REPORT = 'report/QUERY_QUES_RESULT_REPORT'
export const QUERY_QUES_ANWSER_REPORT = 'report/QUERY_QUES_ANWSER_REPORT'

export const SET_REPORT_HEADER_CONFIG = 'report/SET_REPORT_HEADER_CONFIG'

export const QUERY_ROBOT_MESSAGE_REPORT = 'report/query_robot_message_report'
export const QUERY_ROBOT_TOP20_REPORT = 'report/query_robot_top20_report'
