// 邮件状态
export const SET_EMAIL_AUTOCLAIM = 'email/SET_EMAIL_AUTOCLAIM'
export const SET_EMAIL_UNDEALNUM = 'email/SET_EMAIL_UNDEALNUM'
export const SET_EMAIL_TODONUM = 'email/SET_EMAIL_TODONUM'
export const SET_EMAIL_MODULE_READ = 'email/SET_EMAIL_MODULE_READ'
export const SET_EMAIL_SEND_STATUS = 'email/SET_EMAIL_SEND_STATUS'

// 邮件列表
export const QUERY_EMAIL_LIST = 'email/QUERY_EMAIL_LIST'
export const UPDATE_EMAIL_LIST = 'email/UPDATE_EMAIL_LIST'
export const UPDATE_EMAIL_LIST_HISTORY = 'email/UPDATE_EMAIL_LIST_HISTORY'
export const REMOVE_EMAIL_SESSION = 'email/REMOVE_EMAIL_SESSION'
export const BATCH_REMOVE_EMAIL_SESSION = 'email/BATCH_REMOVE_EMAIL_SESSION'

// 邮件详情
export const POPUP_EMAIL_INFO = 'email/POPUP_EMAIL_INFO'
export const LOAD_EMAIL_HISTORY = 'email/LOAD_EMAIL_HISTORY'
export const GET_LAST_EMAIL = 'email/GET_LAST_EMAIL'
export const REPLY_EMAIL_INBOX = 'email/REPLY_EMAIL_INBOX'
export const FORWARD_EMAIL = 'email/FORWARD_EMAIL'
export const SAVE_EMAIL_REMARK = 'email/SAVE_EMAIL_REMARK'
export const REFRESH_EMAIL_LEAKNUM = 'email/REFRESH_EMAIL_LEAKNUM'
export const REDIRECT_EMAIL_SESSION = 'email/REDIRECT_EMAIL_SESSION'
export const DO_EMAIL_MARK = 'email/DO_EMAIL_MARK'
export const DEFINE_EMAIL_CATEGORY = 'email/DEFINE_EMAIL_CATEGORY'

// 邮件客户相关
export const UPDATE_EMAIL_RELATION_CUSTOMER = 'email/UPDATE_EMAIL_RELATION_CUSTOMER'
export const DELETE_EMAIL_RELATION_CUSTOMER = 'email/DELETE_EMAIL_RELATION_CUSTOMER'
export const EMAIL_LOCATION_CUSTOMER = 'email/EMAIL_LOCATION_CUSTOMER'

// 邮件快捷回复相关
export const SAVE_QUICK_REPLY = 'email/SAVE_QUICK_REPLY'
export const GET_QUICK_REPLY_LIST = 'email/GET_QUICK_REPLY_LIST'
export const GET_ALL_QUICK_REPLY_LIST = 'email/GET_ALL_QUICK_REPLY_LIST'
export const QUERY_EMAIL_ALL_TAGS = 'email/QUERY_EMAIL_ALL_TAGS'
export const QUERY_EMAIL_ALL_TAGS_CHILDREN = 'email/QUERY_EMAIL_ALL_TAGS_CHILDREN'
export const SET_QUICK_REPLY_LIST_BY_RDATA = 'email/SET_QUICK_REPLY_LIST_BY_RDATA'
export const DEL_QUICK_REPLY_LIST_BY_RDATA = 'email/DEL_QUICK_REPLY_LIST_BY_RDATA'
export const EDIT_QUICK_REPLY_LIST_BY_RDATA = 'email/EDIT_QUICK_REPLY_LIST_BY_RDATA'
export const SET_CUST_QUICK_REPLY = 'email/SET_CUST_QUICK_REPLY'
